### ISSUE TITLE
Abris waypoint off by ~300 m. PVI route off by >800 m

### ISSUE THREAD

**Issue by JayJ501** [okopanja/SharkPlanner#6]
![Screen_230219_114340](https://user-images.githubusercontent.com/125592286/219943274-ccec9fa1-14c8-4017-9dda-f553506bc4b5.jpg)
![Screen_230219_114328](https://user-images.githubusercontent.com/125592286/219943279-a25743e4-717b-421e-85f1-092ea3d075c1.jpg)

Mission is Ka-50 III instant action caucasus free flight

**Comment by okopanja** [comment]
This issue is not fully resolved but we reached the maximum imposed by limitations of black shark ABRIS itself. The movement of helicopter imposed by the time needed to enter 2 coordinates mean there will be always slight error. I believe this error is now less than 100m, which still makes the feature usable.

Closing the ticket.
